---
swagger: "2.0"
info:
  version: "0.0.0"
  title: "ECPCRM API"
basePath: "/restful"
paths:
  /:
    get:
      tags:
      - "> restful objects supporting resources"
      description: "RO Spec v1.0, section 5.1"
      produces:
      - "application/json"
      - "application/json;profile=urn:org.restfulobjects:repr-types/home-page"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/RestfulObjectsSupportingHomePageRepr"
          headers:
            Cache-Control:
              type: "integer"
              format: "int32"
              description: "RO Spec v1.0, section 2.13"
              default: 86400
  /objects/org.incode.eurocommercial.ecpcrm.dom.card.Card/{objectId}:
    get:
      tags:
      - "card"
      description: "RO Spec v1.0, section 14.1"
      produces:
      - "application/json;profile=urn:org.apache.isis/v1"
      - "application/json;profile=urn:org.apache.isis/v1;suppress=true"
      - "application/json;profile=urn:org.restfulobjects:repr-types/object"
      parameters:
      - name: "objectId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "org.incode.eurocommercial.ecpcrm.dom.card.Card , if Accept:\
            \ application/json;profile=urn:org.apache.isis/v1"
          schema:
            $ref: "#/definitions/org.incode.eurocommercial.ecpcrm.dom.card.CardRepr"
definitions:
  org.incode.eurocommercial.ecpcrm.dom.card.CardRepr:
    type: "object"
    properties:
      datanucleusIdLong:
        type: "integer"
        format: "int64"
      datanucleusVersionLong:
        type: "integer"
        format: "int64"
      datanucleusVersionTimestamp:
        type: "integer"
        format: "int64"
      center:
        $ref: "#/definitions/HrefRepr"
      clientId:
        type: "string"
      number:
        type: "string"
      status:
        type: "string"
        enum:
        - "ENABLED"
        - "DISABLED"
        - "LOST"
        - "TOCHANGE"
    description: "org.incode.eurocommercial.ecpcrm.dom.card.Card (org.incode.eurocommercial.ecpcrm.dom.card.Card)"
  org.incode.eurocommercial.ecpcrm.dom.center.CenterRepr:
    type: "object"
    properties:
      datanucleusIdLong:
        type: "integer"
        format: "int64"
      datanucleusVersionLong:
        type: "integer"
        format: "int64"
      datanucleusVersionTimestamp:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      reference:
        type: "string"
    description: "org.incode.eurocommercial.ecpcrm.dom.center.Center (org.incode.eurocommercial.ecpcrm.dom.center.Center)"
  org.incode.eurocommercial.ecpcrm.dom.person.PersonRepr:
    type: "object"
    properties:
      title:
        type: "string"
        enum:
        - "MR"
        - "MRS"
        - "MISS"
        - "UNKNOWN_IMPORT"
      firstName:
        type: "string"
      lastName:
        type: "string"
      gender:
        type: "string"
        enum:
        - "MALE"
        - "FEMALE"
        - "UNKNOWN_IMPORT"
      datanucleusIdLong:
        type: "integer"
        format: "int64"
      datanucleusVersionLong:
        type: "integer"
        format: "int64"
      datanucleusVersionTimestamp:
        type: "integer"
        format: "int64"
      birthDate:
        type: "string"
        format: "date"
    description: "org.incode.eurocommercial.ecpcrm.dom.person.Person (org.incode.eurocommercial.ecpcrm.dom.person.Person)"
  org.incode.eurocommercial.ecpcrm.dom.user.UserRepr:
    type: "object"
    properties:
      lastName:
        type: "string"
      datanucleusVersionLong:
        type: "integer"
        format: "int64"
      gender:
        type: "string"
        enum:
        - "MALE"
        - "FEMALE"
        - "UNKNOWN_IMPORT"
      center:
        $ref: "#/definitions/HrefRepr"
      datanucleusVersionTimestamp:
        type: "integer"
        format: "int64"
      title:
        type: "string"
        enum:
        - "MR"
        - "MRS"
        - "MISS"
        - "UNKNOWN_IMPORT"
      datanucleusIdLong:
        type: "integer"
        format: "int64"
      birthDate:
        type: "string"
        format: "date"
      enabled:
        type: "boolean"
      firstName:
        type: "string"
      promotionalEmails:
        type: "boolean"
      email:
        type: "string"
      card:
        $ref: "#/definitions/HrefRepr"
    description: "org.incode.eurocommercial.ecpcrm.dom.user.User (org.incode.eurocommercial.ecpcrm.dom.user.User)"