---
swagger: "2.0"
info:
  version: "0.0.0"
  title: "ECPCRM API"
basePath: "/restful"
paths:
  /:
    get:
      tags:
      - "> restful objects supporting resources"
      description: "RO Spec v1.0, section 5.1"
      produces:
      - "application/json"
      - "application/json;profile=urn:org.restfulobjects:repr-types/home-page"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/RestfulObjectsSupportingHomePageRepr"
          headers:
            Cache-Control:
              type: "integer"
              format: "int32"
              description: "RO Spec v1.0, section 2.13"
              default: 86400
  /objects/org.incode.eurocommercial.ecpcrm.dom.card.Card/{objectId}:
    get:
      tags:
      - "card"
      description: "RO Spec v1.0, section 14.1"
      produces:
      - "application/json;profile=urn:org.apache.isis/v1"
      - "application/json;profile=urn:org.apache.isis/v1;suppress=true"
      - "application/json;profile=urn:org.restfulobjects:repr-types/object"
      parameters:
      - name: "objectId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "org.incode.eurocommercial.ecpcrm.dom.card.Card , if Accept:\
            \ application/json;profile=urn:org.apache.isis/v1"
          schema:
            $ref: "#/definitions/org.incode.eurocommercial.ecpcrm.dom.card.CardRepr"
definitions:
  org.incode.eurocommercial.ecpcrm.dom.card.CardRepr:
    type: "object"
    properties:
      datanucleusIdLong:
        type: "integer"
        format: "int64"
      datanucleusVersionLong:
        type: "integer"
        format: "int64"
      datanucleusVersionTimestamp:
        type: "integer"
        format: "int64"
      center:
        $ref: "#/definitions/HrefRepr"
      clientId:
        type: "string"
      number:
        type: "string"
      status:
        type: "string"
        enum:
        - "ENABLED"
        - "DISABLED"
        - "LOST"
        - "TOCHANGE"
    description: "org.incode.eurocommercial.ecpcrm.dom.card.Card (org.incode.eurocommercial.ecpcrm.dom.card.Card)"
  org.incode.eurocommercial.ecpcrm.dom.center.CenterRepr:
    type: "object"
    properties:
      datanucleusIdLong:
        type: "integer"
        format: "int64"
      datanucleusVersionLong:
        type: "integer"
        format: "int64"
      datanucleusVersionTimestamp:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      reference:
        type: "string"
    description: "org.incode.eurocommercial.ecpcrm.dom.center.Center (org.incode.eurocommercial.ecpcrm.dom.center.Center)"
  org.incode.eurocommercial.ecpcrm.dom.person.PersonRepr:
    type: "object"
    properties:
      title:
        type: "string"
        enum:
        - "MR"
        - "MRS"
        - "MISS"
        - "UNKNOWN_IMPORT"
      firstName:
        type: "string"
      lastName:
        type: "string"
      gender:
        type: "string"
        enum:
        - "MALE"
        - "FEMALE"
        - "UNKNOWN_IMPORT"
      datanucleusIdLong:
        type: "integer"
        format: "int64"
      datanucleusVersionLong:
        type: "integer"
        format: "int64"
      datanucleusVersionTimestamp:
        type: "integer"
        format: "int64"
      birthDate:
        type: "string"
        format: "date"
    description: "org.incode.eurocommercial.ecpcrm.dom.person.Person (org.incode.eurocommercial.ecpcrm.dom.person.Person)"
  org.incode.eurocommercial.ecpcrm.dom.user.UserRepr:
    type: "object"
    properties:
      lastName:
        type: "string"
      datanucleusVersionLong:
        type: "integer"
        format: "int64"
      gender:
        type: "string"
        enum:
        - "MALE"
        - "FEMALE"
        - "UNKNOWN_IMPORT"
      center:
        $ref: "#/definitions/HrefRepr"
      datanucleusVersionTimestamp:
        type: "integer"
        format: "int64"
      title:
        type: "string"
        enum:
        - "MR"
        - "MRS"
        - "MISS"
        - "UNKNOWN_IMPORT"
      datanucleusIdLong:
        type: "integer"
        format: "int64"
      birthDate:
        type: "string"
        format: "date"
      enabled:
        type: "boolean"
      firstName:
        type: "string"
      promotionalEmails:
        type: "boolean"
      email:
        type: "string"
      card:
        $ref: "#/definitions/HrefRepr"
    description: "org.incode.eurocommercial.ecpcrm.dom.user.User (org.incode.eurocommercial.ecpcrm.dom.user.User)"      names:
        type: string
      count:
        type: integer
    description: ChildCare

responses:
  InvalidRequest: # 300
    description: Invalid request
    schema:
      $ref: "#/definitions/Error"
  InvalidDevice: # 301
    description: Invalid device
    schema:
      $ref: "#/definitions/Error"
  InvalidParam: # 302
    description: A required parameter is missing or invalid
    schema:
      $ref: "#/definitions/Error"
  InvalidCard: # 303
    description: Invalid card
    schema:
      $ref: "#/definitions/Error"
  InvalidUser: # 304
    description: Invalid user
    schema:
      $ref: "#/definitions/Error"
  EmailExists: # 305, 309, (306)
    description: Email already exists in our system
    schema:
      $ref: "#/definitions/Error"
  EmailExistsInvalidCheck: # 306 -- TODO: This seems duplicate
    description: Email already exists in our system, user doesn't match
    schema:
      $ref: "#/definitions/Error"
  CardRequestHandled: # 307
    description: User already requested a card, which has been handled
    schema:
      $ref: "#/definitions/Error"
  CardAlreadyBoundAnotherUser: # 308
    description: Card is already bound to another user
    schema:
      $ref: "#/definitions/Error"
  EmailExistsWhenCreatingOrUpdating: # 309 -- TODO: This seems duplicate
    description: Email already exists in our system
    schema:
      $ref: "#/definitions/Error"
  InvalidAccess: # 310
    description: Invalid access
    schema:
      $ref: "#/definitions/Error"
  InvalidCardRequest: # 311
    description: Invalid card request
    schema:
      $ref: "#/definitions/Error"
  InvalidCardNumber: # 312
    description: Invalid card number
    schema:
      $ref: "#/definitions/Error"
  FailedUserCardCreate: # 313
    description: Failed to create user for card
    schema:
      $ref: "#/definitions/Error"
  FailedUserCardBind: # 314
    description: Failed to bind user to card
    schema:
      $ref: "#/definitions/Error"
  UserAlreadyPlayed: # 315
    description: User has already played
    schema:
      $ref: "#/definitions/Error"
  FailedUserUpdateCreate: # 316
    description: Failed to create or update user
    schema:
      $ref: "#/definitions/Error"
  InvalidCenterCard: # 317
    description: This card is not valid for this center
    schema:
      $ref: "#/definitions/Error"
  CardLost: # 318
    description: Email exists, and is linked to this user, perhaps the card is lost
    schema:
      $ref: "#/definitions/Error"
  CardOutdated: # 319
    description: This card is outdated, it needs to be replaced
